INSERT INTO
  state_master(stateCode,stateName,createdAt,updatedAt)
VALUES
  ('AP','Andhra Pradesh',sysdate(),sysdate()),
  ('AR','Arunachal Pradesh',sysdate(),sysdate()),
    ('AS','Assam',sysdate(),sysdate()),
    ('BR','Bihar',sysdate(),sysdate()),
    ('CG','Chhattisgarh',sysdate(),sysdate()),
    ('GA','Goa',sysdate(),sysdate()),
    ('GJ','Gujarat',sysdate(),sysdate()),
    ('HR','Haryana',sysdate(),sysdate()),
    ('HP','Himachal Pradesh',sysdate(),sysdate()),
    ('JH','Jharkhand',sysdate(),sysdate()),
    ('KA','Karnataka',sysdate(),sysdate()),
    ('KL','Kerala',sysdate(),sysdate()),
    ('MP','Madhya Pradesh',sysdate(),sysdate()),
    ('MH','Maharashtra',sysdate(),sysdate()),
    ('MN','Manipur',sysdate(),sysdate()),
    ('ML','Meghalaya',sysdate(),sysdate()),
    ('MZ','Mizoram',sysdate(),sysdate()),
    ('NL','Nagaland',sysdate(),sysdate()),
    ('OD','Odisha',sysdate(),sysdate()),
    ('PB','Punjab',sysdate(),sysdate()),
    ('RJ','Rajasthan',sysdate(),sysdate()),
    ('SK','Sikkim',sysdate(),sysdate()),
    ('TN','Tamil Nadu',sysdate(),sysdate()),
    ('TS','Telangana',sysdate(),sysdate()),
    ('TR','Tripura',sysdate(),sysdate()),
    ('UP','Uttar Pradesh',sysdate(),sysdate()),
    ('UK','Uttarakhand',sysdate(),sysdate()),
    ('WB','West Bengal',sysdate(),sysdate());